language: objective-c
osx_image: xcode7.3
script: set -o pipefail && xcodebuild test -project Calcula\ Tu\ Salario.xcodeproj -scheme Calcula\ Tu\ Salario -sdk iphonesimulator9.3 | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Calcula Tu Salario'
